# Generated by Django 3.1.1 on 2020-10-02 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dscblog', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('info', models.CharField(default=None, max_length=60, null=True, verbose_name='Info')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dscblog.blog')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
            ],
        ),
    ]
