# Generated by Django 3.1.1 on 2020-10-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscblog', '0005_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='info',
            field=models.CharField(blank=True, default=None, max_length=60, verbose_name='Info'),
        ),
    ]
