# Generated by Django 3.1.1 on 2020-10-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscblog', '0006_auto_20201002_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Bio'),
        ),
    ]
