# Generated by Django 3.1.1 on 2020-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscblog', '0013_auto_20201030_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='Engagement Score'),
        ),
    ]
