# Generated by Django 3.1.1 on 2020-11-02 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('dscblog', '0014_blog_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=1.0, verbose_name='Engagement Score')),
                ('date', models.DateTimeField()),
                ('key', models.CharField(max_length=30, verbose_name='Key')),
                ('pingbacks', models.IntegerField(default=0)),
                ('last_pingback_date', models.DateTimeField(default=None, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='dscblog.blog')),
                ('session', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed', to='sessions.session')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
