# Generated by Django 3.1.1 on 2020-11-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscblog', '0016_auto_20201104_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='referer',
            field=models.CharField(default=None, max_length=400, null=True, verbose_name='Referer Site'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img_url',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
