# Generated by Django 3.1.1 on 2020-12-30 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dscblog', '0018_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_alert_email_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_email_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_newsletters',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='ref_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_refs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
