# Generated by Django 3.1.1 on 2020-12-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscblog', '0018_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
