# Generated by Django 3.1.1 on 2020-12-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dscblog', '0019_blog_is_subscribed'),
        ('dscblog', '0019_auto_20201230_0846'),
    ]

    operations = [
    ]
